# Generated by Django 3.1.7 on 2021-04-25 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_auto_20210409_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('agua', models.IntegerField()),
                ('ejercicio', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('estres', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(max_length=300)),
                ('agua', models.IntegerField()),
                ('ejercicio', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('estres', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(max_length=300)),
                ('agua', models.IntegerField()),
                ('ejercicio', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('estres', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.registro')),
            ],
        ),
    ]
