# Generated by Django 3.1.7 on 2021-05-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20210427_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='registro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estres',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='estres',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportegeneral',
            name='estres',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
