# Generated by Django 3.1.7 on 2021-05-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20210515_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='registro',
        ),
        migrations.AddField(
            model_name='registro',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.test'),
        ),
    ]
