# Generated by Django 3.1.7 on 2021-05-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20210518_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
