# Generated by Django 3.1.7 on 2021-05-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210518_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='fechaIn',
            field=models.DateField(null=True),
        ),
    ]
