# Generated by Django 3.1.7 on 2021-05-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0018_auto_20210519_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportediario',
            name='registro',
        ),
        migrations.AddField(
            model_name='reportediario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
