# Generated by Django 3.1.7 on 2021-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20210520_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegeneral',
            name='agua',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportegeneral',
            name='ejercicio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportegeneral',
            name='sleep',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
