# Generated by Django 3.1.7 on 2021-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20210521_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='agua',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8+')]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ejercicio',
            field=models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40+')]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sleep',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8+')]),
        ),
    ]
