# Generated by Django 3.1.7 on 2021-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20210526_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='agua',
            field=models.IntegerField(choices=[(0, '0 vasos'), (1, '1 vaso'), (2, '2 vasos'), (3, '3 vasos'), (4, '4 vasos'), (5, '5 vasos'), (6, '6 vasos'), (7, '7 vasos'), (8, '8+ vasos')]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ejercicio',
            field=models.IntegerField(choices=[(0, '0 minutos'), (10, '10 minutos'), (20, '20 minutos'), (30, '30 minutos'), (40, '40+ minutos')]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sleep',
            field=models.IntegerField(choices=[(0, '0 horas'), (1, '1 hora'), (2, '2 horas'), (3, '3 horas'), (4, '4 horas'), (5, '5 horas'), (6, '6 horas'), (7, '7 horas'), (8, '8+ horas')]),
        ),
    ]
