# Generated by Django 3.1.7 on 2021-06-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20210528_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportediario',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='reportegeneral',
            name='comentarios',
        ),
    ]
