# Generated by Django 3.1.7 on 2021-05-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_respuesta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='user',
        ),
    ]
